version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo === INSTALL CFN-LINT ===
      - pip3 install cfn-lint

  pre_build:          
    commands:
      - echo === CHECKING FOR PYTHON INSTALL ===
      - python3 --version
      - echo === CHECKING FOR AWS CLI INSTALL ===
      - aws --version
      - echo === CHECKING FOR CFN-LINT INSTALL ===
      - cfn-lint --version

  build:
    commands:
      - echo === Test the template ===
      - cfn-lint template.yml
      - echo === template test completed ===
      - echo === BUILD THE TEMPLATE ===
      - aws cloudformation package --template-file template.yml --s3-bucket nwudodevopsbucket --output-template-file build-artifact.yml

  post_build:
    commands:
      - echo === ACTION TO TAKE WHEN BUILD IS COMPLETE ===
      - echo Build completed at `date`...

artifacts:
  files:
    - build-artifact.yml
