AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 instance with Apache web server

Parameters:
  SecurityGroupId:
    Description: Security Group ID that allows HTTP (80) and SSH (22)
    Type: AWS::EC2::SecurityGroup::Id

Mappings: 
  RegionMap: 
    us-east-1: 
      AMI: ami-0532be01f26a3de55
    us-west-1: 
      AMI: ami-0993d3759749c153c

  RegionSubnetMap:
    us-east-1:
      SubnetId: subnet-07af715769b426119
    us-west-1:
      SubnetId: subnet-0efeff9d25d8d403f

Resources:
  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", AMI]
      InstanceType: t2.micro
      SecurityGroupIds:
        - !Ref SecurityGroupId
      SubnetId: !FindInMap [RegionSubnetMap, !Ref "AWS::Region", SubnetId]
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "NWUDO CHIKAEZE" > /var/www/html/index.html

Outputs:
  WebServerPublicIP:
    Description: Public IP address of the EC2 instance
    Value: !GetAtt WebServer.PublicIp
